# Generated by Django 2.1.2 on 2018-10-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.IntegerField(null=True)),
                ('organization', models.CharField(max_length=500, null=True)),
                ('kpi', models.CharField(max_length=500, null=True)),
                ('kpi_sub', models.CharField(max_length=500, null=True)),
                ('value', models.IntegerField(null=True)),
                ('comments', models.CharField(max_length=500, null=True)),
                ('unit', models.CharField(max_length=500, null=True)),
                ('date', models.CharField(max_length=500, null=True)),
                ('period', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
